/*
  DO NOT EDIT THIS FILE
  This header was autogenerated from:
  http://www.alien.net.au/irc/irc2numerics.def

  This file is released as public domain for the IRC community.
  Copyright (c) 2001,2002,2003,2004 Simon Butcher <pickle@alien.net.au>
*/

#define RPL_WELCOME                              001 // :Welcome to the Internet Relay Network <nick>!<user>@<host>
#define RPL_YOURHOST                             002 // :Your host is <servername>, running version <version>
#define RPL_CREATED                              003 // :This server was created <date>
#define RPL_MYINFO                               004 // <server_name> <version> <user_modes> <chan_modes>
#define RPL_MYINFO_KINEIRCD                      004 // <server_name> <version> <user_modes> <chan_modes> <channel_modes_with_params> <user_modes_with_params> <server_modes> <server_modes_with_params>
#define RPL_ISUPPORT                             005
#define RPL_MAP_UNREAL                           006
#define RPL_MAPEND_UNREAL                        007
#define RPL_SNOMASK_IRCU                         008
#define RPL_STATMEMTOT_IRCU                      009
#define RPL_BOUNCE                               010 // <hostname> <port> :<info>
#define RPL_YOURCOOKIE_HYBRID                    014
#define RPL_MAP_IRCU                             015
#define RPL_MAPMORE_IRCU                         016
#define RPL_MAPEND_IRCU                          017
#define RPL_YOURID_IRCNET                        042
#define RPL_SAVENICK_IRCNET                      043 // :<info>
#define RPL_ATTEMPTINGJUNC_AIRCD                 050
#define RPL_ATTEMPTINGREROUTE_AIRCD              051
#define RPL_TRACELINK                            200 // Link <version>[.<debug_level>] <destination> <next_server> [V<protocol_version> <link_uptime_in_seconds> <backstream_sendq> <upstream_sendq>]
#define RPL_TRACECONNECTING                      201 // Try. <class> <server>
#define RPL_TRACEHANDSHAKE                       202 // H.S. <class> <server>
#define RPL_TRACEUNKNOWN                         203 // ???? <class> [<connection_address>]
#define RPL_TRACEOPERATOR                        204 // Oper <class> <nick>
#define RPL_TRACEUSER                            205 // User <class> <nick>
#define RPL_TRACESERVER                          206 // Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server> [V<protocol_version>]
#define RPL_TRACESERVICE                         207 // Service <class> <name> <type> <active_type>
#define RPL_TRACENEWTYPE                         208 // <newtype> 0 <client_name>
#define RPL_TRACECLASS                           209 // Class <class> <count>
#define RPL_STATS_AIRCD                          210
#define RPL_STATSLINKINFO                        211 // <linkname> <sendq> <sent_msgs> <sent_bytes> <recvd_msgs> <rcvd_bytes> <time_open>
#define RPL_STATSCOMMANDS                        212 // <command> <count> [<byte_count> <remote_count>]
#define RPL_STATSCLINE                           213 // C <host> * <name> <port> <class>
#define RPL_STATSNLINE_RFC1459                   214 // N <host> * <name> <port> <class>
#define RPL_STATSILINE                           215 // I <host> * <host> <port> <class>
#define RPL_STATSKLINE                           216 // K <host> * <username> <port> <class>
#define RPL_STATSQLINE_RFC1459                   217
#define RPL_STATSPLINE_IRCU                      217
#define RPL_STATSYLINE                           218 // Y <class> <ping_freq> <connect_freq> <max_sendq>
#define RPL_ENDOFSTATS                           219 // <query> :<info>
#define RPL_STATSPLINE_HYBRID                    220
#define RPL_STATSBLINE_BAHAMUT_UNREAL            220
#define RPL_UMODEIS                              221 // <user_modes> [<user_mode_params>]
#define RPL_MODLIST                              222
#define RPL_SQLINE_NICK_UNREAL                   222
#define RPL_STATSBLINE_BAHAMUT                   222
#define RPL_STATSELINE_BAHAMUT                   223
#define RPL_STATSGLINE_UNREAL                    223
#define RPL_STATSFLINE_HYBRID_BAHAMUT            224
#define RPL_STATSTLINE_UNREAL                    224
#define RPL_STATSDLINE_HYBRID                    225
#define RPL_STATSZLINE_BAHAMUT                   225
#define RPL_STATSELINE_UNREAL                    225
#define RPL_STATSCOUNT_BAHAMUT                   226
#define RPL_STATSNLINE_UNREAL                    226
#define RPL_STATSGLINE_BAHAMUT                   227
#define RPL_STATSVLINE_UNREAL                    227
#define RPL_STATSQLINE_IRCU                      228
#define RPL_RULES_UNREAL                         232
#define RPL_SERVLIST                             234 // <name> <server> <mask> <type> <hopcount> <info>
#define RPL_SERVLISTEND                          235 // <mask> <type> :<info>
#define RPL_STATSVERBOSE_IRCU                    236
#define RPL_STATSENGINE_IRCU                     237
#define RPL_STATSFLINE_IRCU                      238
#define RPL_STATSIAUTH_IRCNET                    239
#define RPL_STATSVLINE_RFC2812                   240
#define RPL_STATSXLINE_AUSTHEX                   240
#define RPL_STATSLLINE                           241 // L <hostmask> * <servername> <maxdepth>
#define RPL_STATSUPTIME                          242 // :Server Up <days> days <hours>:<minutes>:<seconds>
#define RPL_STATSOLINE                           243 // O <hostmask> * <nick> [:<info>]
#define RPL_STATSHLINE                           244 // H <hostmask> * <servername>
#define RPL_STATSSLINE_BAHAMUT_IRCNET_HYBRID     245
#define RPL_STATSTLINE_IRCU                      246
#define RPL_STATSULINE_HYBRID                    246
#define RPL_STATSBLINE_RFC2812                   247
#define RPL_STATSXLINE_HYBRID_PTLINK_UNREAL      247
#define RPL_STATSGLINE_IRCU                      247
#define RPL_STATSULINE_IRCU                      248
#define RPL_STATSDEFINE_IRCNET                   248
#define RPL_STATSULINE                           249
#define RPL_STATSDEBUG_HYBRID                    249
#define RPL_STATSDLINE_RFC2812                   250
#define RPL_STATSCONN_IRCU_UNREAL                250
#define RPL_LUSERCLIENT                          251 // :There are <int> users and <int> invisible on <int> servers
#define RPL_LUSEROP                              252 // <int> :<info>
#define RPL_LUSERUNKNOWN                         253 // <int> :<info>
#define RPL_LUSERCHANNELS                        254 // <int> :<info>
#define RPL_LUSERME                              255 // :I have <int> clients and <int> servers
#define RPL_ADMINME                              256 // <server> :<info>
#define RPL_ADMINLOC1                            257 // :<admin_location>
#define RPL_ADMINLOC2                            258 // :<admin_location>
#define RPL_ADMINEMAIL                           259 // :<email_address>
#define RPL_TRACELOG                             261 // File <logfile> <debug_level>
#define RPL_TRACEPING                            262
#define RPL_TRACEEND_RFC2812                     262 // <server_name> <version>[.<debug_level>] :<info>
#define RPL_TRYAGAIN                             263 // <command> :<info>
#define RPL_LOCALUSERS_AIRCD_HYBRID_HYBRID_BAHAMUT 265
#define RPL_GLOBALUSERS_AIRCD_HYBRID_HYBRID_BAHAMUT 266
#define RPL_START_NETSTAT_AIRCD                  267
#define RPL_NETSTAT_AIRCD                        268
#define RPL_END_NETSTAT_AIRCD                    269
#define RPL_PRIVS_IRCU                           270
#define RPL_SILELIST_IRCU                        271
#define RPL_ENDOFSILELIST_IRCU                   272
#define RPL_NOTIFY_AIRCD                         273
#define RPL_ENDNOTIFY_AIRCD                      274
#define RPL_STATSDELTA_IRCNET                    274
#define RPL_STATSDLINE_IRCU_ULTIMATE             275
#define RPL_VCHANEXIST                           276
#define RPL_VCHANLIST                            277
#define RPL_VCHANHELP                            278
#define RPL_GLIST_IRCU                           280
#define RPL_ENDOFGLIST_IRCU                      281
#define RPL_ACCEPTLIST                           281
#define RPL_ENDOFACCEPT                          282
#define RPL_JUPELIST_IRCU                        282
#define RPL_ALIST                                283
#define RPL_ENDOFJUPELIST_IRCU                   283
#define RPL_ENDOFALIST                           284
#define RPL_FEATURE_IRCU                         284
#define RPL_GLIST_HASH                           285
#define RPL_CHANINFO_HANDLE_AIRCD                285
#define RPL_NEWHOSTIS_QUAKENET                   285
#define RPL_CHANINFO_USERS_AIRCD                 286
#define RPL_CHKHEAD_QUAKENET                     286
#define RPL_CHANINFO_CHOPS_AIRCD                 287
#define RPL_CHANUSER_QUAKENET                    287
#define RPL_CHANINFO_VOICES_AIRCD                288
#define RPL_PATCHHEAD_QUAKENET                   288
#define RPL_CHANINFO_AWAY_AIRCD                  289
#define RPL_PATCHCON_QUAKENET                    289
#define RPL_CHANINFO_OPERS_AIRCD                 290
#define RPL_HELPHDR_UNREAL                       290
#define RPL_DATASTR_QUAKENET                     290
#define RPL_CHANINFO_BANNED_AIRCD                291
#define RPL_HELPOP_UNREAL                        291
#define RPL_ENDOFCHECK_QUAKENET                  291
#define RPL_CHANINFO_BANS_AIRCD                  292
#define RPL_HELPTLR_UNREAL                       292
#define RPL_CHANINFO_INVITE_AIRCD                293
#define RPL_HELPHLP_UNREAL                       293
#define RPL_CHANINFO_INVITES_AIRCD               294
#define RPL_HELPFWD_UNREAL                       294
#define RPL_CHANINFO_KICK_AIRCD                  295
#define RPL_HELPIGN_UNREAL                       295
#define RPL_CHANINFO_KICKS_AIRCD                 296
#define RPL_END_CHANINFO_AIRCD                   299
#define RPL_NONE                                 300
#define RPL_AWAY                                 301 // <nick> :<message>
#define RPL_AWAY_KINEIRCD                        301 // <nick> <seconds away> :<message>
#define RPL_USERHOST                             302 // :*1<reply> *( ' ' <reply> )
#define RPL_ISON                                 303 // :*1<nick> *( ' ' <nick> )
#define RPL_UNAWAY                               305 // :<info>
#define RPL_NOWAWAY                              306 // :<info>
#define RPL_USERIP                               307
#define RPL_WHOISREGNICK_BAHAMUT_UNREAL          307
#define RPL_SUSERHOST_AUSTHEX                    307
#define RPL_NOTIFYACTION_AIRCD                   308
#define RPL_WHOISADMIN_BAHAMUT                   308
#define RPL_RULESSTART_UNREAL                    308
#define RPL_NICKTRACE_AIRCD                      309
#define RPL_WHOISSADMIN_BAHAMUT                  309
#define RPL_ENDOFRULES_UNREAL                    309
#define RPL_WHOISHELPER_AUSTHEX                  309
#define RPL_WHOISSVCMSG_BAHAMUT                  310
#define RPL_WHOISHELPOP_UNREAL                   310
#define RPL_WHOISSERVICE_AUSTHEX                 310
#define RPL_WHOISUSER                            311 // <nick> <user> <host> * :<real_name>
#define RPL_WHOISSERVER                          312 // <nick> <server> :<server_info>
#define RPL_WHOISOPERATOR                        313 // <nick> :<privileges>
#define RPL_WHOWASUSER                           314 // <nick> <user> <host> * :<real_name>
#define RPL_ENDOFWHO                             315 // <name> :<info>
#define RPL_WHOISIDLE                            317 // <nick> <seconds> :seconds idle
#define RPL_ENDOFWHOIS                           318 // <nick> :<info>
#define RPL_WHOISCHANNELS                        319 // <nick> :*( ( '@' / '+' ) <channel> ' ' )
#define RPL_WHOISVIRT_AUSTHEX                    320
#define RPL_WHOIS_HIDDEN_ANOTHERNET              320
#define RPL_WHOISSPECIAL_UNREAL                  320
#define RPL_LIST                                 322 // <channel> <#_visible> :<topic>
#define RPL_LISTEND                              323 // :<info>
#define RPL_CHANNELMODEIS                        324 // <channel> <mode> <mode_params>
#define RPL_UNIQOPIS_RFC2812                     325 // <channel> <nickname>
#define RPL_CHANNELPASSIS                        325
#define RPL_NOCHANPASS                           326
#define RPL_CHPASSUNKNOWN                        327
#define RPL_CHANNEL_URL_BAHAMUT_AUSTHEX          328
#define RPL_CREATIONTIME_BAHAMUT                 329
#define RPL_WHOWAS_TIME                          330
#define RPL_WHOISACCOUNT_IRCU                    330 // <nick> <authname> :<info>
#define RPL_NOTOPIC                              331 // <channel> :<info>
#define RPL_TOPIC                                332 // <channel> :<topic>
#define RPL_TOPICWHOTIME_IRCU                    333
#define RPL_LISTUSAGE_IRCU                       334
#define RPL_COMMANDSYNTAX_BAHAMUT                334
#define RPL_LISTSYNTAX_UNREAL                    334
#define RPL_WHOISBOT_UNREAL                      335
#define RPL_CHANPASSOK                           338
#define RPL_WHOISACTUALLY_IRCU_BAHAMUT           338
#define RPL_BADCHANPASS                          339
#define RPL_USERIP_IRCU                          340
#define RPL_INVITING                             341 // <nick> <channel>
#define RPL_INVITED_GAMESURGE                    345 // <channel> <user being invited> <user issuing invite> :<user being invited> has been invited by <user issuing invite>
#define RPL_INVITELIST                           346 // <channel> <invitemask>
#define RPL_ENDOFINVITELIST                      347 // <channel> :<info>
#define RPL_EXCEPTLIST                           348 // <channel> <exceptionmask>
#define RPL_ENDOFEXCEPTLIST                      349 // <channel> :<info>
#define RPL_VERSION                              351 // <version>[.<debuglevel>] <server> :<comments>
#define RPL_WHOREPLY                             352 // <channel> <user> <host> <server> <nick> <H|G>[*][@|+] :<hopcount> <real_name>
#define RPL_NAMREPLY                             353 // ( '=' / '*' / '@' ) <channel> ' ' : [ '@' / '+' ] <nick> *( ' ' [ '@' / '+' ] <nick> )
#define RPL_WHOSPCRPL_IRCU                       354
#define RPL_NAMREPLY_QUAKENET                    355 // ( '=' / '*' / '@' ) <channel> ' ' : [ '@' / '+' ] <nick> *( ' ' [ '@' / '+' ] <nick> )
#define RPL_MAP_AUSTHEX                          357
#define RPL_MAPMORE_AUSTHEX                      358
#define RPL_MAPEND_AUSTHEX                       359
#define RPL_LINKS                                364 // <mask> <server> :<hopcount> <server_info>
#define RPL_ENDOFLINKS                           365 // <mask> :<info>
#define RPL_ENDOFNAMES                           366 // <channel> :<info>
#define RPL_BANLIST                              367 // <channel> <banid> [<time_left> :<reason>]
#define RPL_ENDOFBANLIST                         368 // <channel> :<info>
#define RPL_ENDOFWHOWAS                          369 // <nick> :<info>
#define RPL_INFO                                 371 // :<string>
#define RPL_MOTD                                 372 // :- <string>
#define RPL_ENDOFINFO                            374 // :<info>
#define RPL_MOTDSTART                            375 // :- <server> Message of the day -
#define RPL_ENDOFMOTD                            376 // :<info>
#define RPL_KICKEXPIRED_AIRCD                    377
#define RPL_BANEXPIRED_AIRCD                     378
#define RPL_WHOISHOST_UNREAL                     378
#define RPL_KICKLINKED_AIRCD                     379
#define RPL_WHOISMODES_UNREAL                    379
#define RPL_BANLINKED_AIRCD                      380
#define RPL_YOURHELPER_AUSTHEX                   380
#define RPL_YOUREOPER                            381 // :<info>
#define RPL_REHASHING                            382 // <config_file> :<info>
#define RPL_YOURESERVICE                         383 // :You are service <service_name>
#define RPL_NOTOPERANYMORE_AUSTHEX_HYBRID_UNREAL 385
#define RPL_QLIST_UNREAL                         386
#define RPL_IRCOPS_ULTIMATE                      386
#define RPL_ENDOFQLIST_UNREAL                    387
#define RPL_ENDOFIRCOPS_ULTIMATE                 387
#define RPL_ALIST_UNREAL                         388
#define RPL_ENDOFALIST_UNREAL                    389
#define RPL_TIME                                 391 // <server> :<time string>
#define RPL_TIME_IRCU                            391 // <server> <timestamp> <offset> :<time string>
#define RPL_TIME_BDQ_IRCD                        391 // <server> <timezone name> <microseconds> :<time string>
#define RPL_TIME                                 391 // <server> <year> <month> <day> <hour> <minute> <second>
#define RPL_USERSSTART                           392 // :UserID   Terminal  Host
#define RPL_USERS                                393 // :<username> <ttyline> <hostname>
#define RPL_ENDOFUSERS                           394 // :<info>
#define RPL_NOUSERS                              395 // :<info>
#define RPL_HOSTHIDDEN_UNDERNET                  396
#define ERR_UNKNOWNERROR                         400 // <command> [<?>] :<info>
#define ERR_NOSUCHNICK                           401 // <nick> :<reason>
#define ERR_NOSUCHSERVER                         402 // <server> :<reason>
#define ERR_NOSUCHCHANNEL                        403 // <channel> :<reason>
#define ERR_CANNOTSENDTOCHAN                     404 // <channel> :<reason>
#define ERR_TOOMANYCHANNELS                      405 // <channel> :<reason>
#define ERR_WASNOSUCHNICK                        406 // <nick> :<reason>
#define ERR_TOOMANYTARGETS                       407 // <target> :<reason>
#define ERR_NOSUCHSERVICE                        408 // <service_name> :<reason>
#define ERR_NOCOLORSONCHAN_BAHAMUT               408
#define ERR_NOORIGIN                             409 // :<reason>
#define ERR_NORECIPIENT                          411 // :<reason>
#define ERR_NOTEXTTOSEND                         412 // :<reason>
#define ERR_NOTOPLEVEL                           413 // <mask> :<reason>
#define ERR_WILDTOPLEVEL                         414 // <mask> :<reason>
#define ERR_BADMASK                              415 // <mask> :<reason>
#define ERR_TOOMANYMATCHES_IRCNET                416 // <command> [<mask>] :<info>
#define ERR_QUERYTOOLONG_IRCU                    416
#define ERR_LENGTHTRUNCATED_AIRCD                419
#define ERR_UNKNOWNCOMMAND                       421 // <command> :<reason>
#define ERR_NOMOTD                               422 // :<reason>
#define ERR_NOADMININFO                          423 // <server> :<reason>
#define ERR_FILEERROR                            424 // :<reason>
#define ERR_NOOPERMOTD_UNREAL                    425
#define ERR_TOOMANYAWAY_BAHAMUT                  429
#define ERR_EVENTNICKCHANGE_AUSTHEX              430
#define ERR_NONICKNAMEGIVEN                      431 // :<reason>
#define ERR_ERRONEUSNICKNAME                     432 // <nick> :<reason>
#define ERR_NICKNAMEINUSE                        433 // <nick> :<reason>
#define ERR_SERVICENAMEINUSE_AUSTHEX             434
#define ERR_NORULES_UNREAL_ULTIMATE              434
#define ERR_SERVICECONFUSED_UNREAL               435
#define ERR_BANONCHAN_BAHAMUT                    435
#define ERR_NICKCOLLISION                        436 // <nick> :<reason>
#define ERR_UNAVAILRESOURCE_RFC2812              437 // <nick/channel/service> :<reason>
#define ERR_BANNICKCHANGE_IRCU                   437
#define ERR_NICKTOOFAST_IRCU                     438
#define ERR_DEAD_IRCNET                          438
#define ERR_TARGETTOOFAST_IRCU                   439
#define ERR_SERVICESDOWN_BAHAMUT_UNREAL          440
#define ERR_USERNOTINCHANNEL                     441 // <nick> <channel> :<reason>
#define ERR_NOTONCHANNEL                         442 // <channel> :<reason>
#define ERR_USERONCHANNEL                        443 // <nick> <channel> [:<reason>]
#define ERR_NOLOGIN                              444 // <user> :<reason>
#define ERR_SUMMONDISABLED                       445 // :<reason>
#define ERR_USERSDISABLED                        446 // :<reason>
#define ERR_NONICKCHANGE_UNREAL                  447
#define ERR_NOTIMPLEMENTED_UNDERNET              449 // Unspecified
#define ERR_NOTREGISTERED                        451 // :<reason>
#define ERR_IDCOLLISION                          452
#define ERR_NICKLOST                             453
#define ERR_HOSTILENAME_UNREAL                   455
#define ERR_ACCEPTFULL                           456
#define ERR_ACCEPTEXIST                          457
#define ERR_ACCEPTNOT                            458
#define ERR_NOHIDING_UNREAL                      459
#define ERR_NOTFORHALFOPS_UNREAL                 460
#define ERR_NEEDMOREPARAMS                       461 // <command> :<reason>
#define ERR_ALREADYREGISTERED                    462 // :<reason>
#define ERR_NOPERMFORHOST                        463 // :<reason>
#define ERR_PASSWDMISMATCH                       464 // :<reason>
#define ERR_YOUREBANNEDCREEP                     465 // :<reason>
#define ERR_KEYSET                               467 // <channel> :<reason>
#define ERR_INVALIDUSERNAME_IRCU                 468
#define ERR_ONLYSERVERSCANCHANGE_BAHAMUT_UNREAL  468
#define ERR_LINKSET_UNREAL                       469
#define ERR_LINKCHANNEL_UNREAL                   470
#define ERR_KICKEDFROMCHAN_AIRCD                 470
#define ERR_CHANNELISFULL                        471 // <channel> :<reason>
#define ERR_UNKNOWNMODE                          472 // <char> :<reason>
#define ERR_INVITEONLYCHAN                       473 // <channel> :<reason>
#define ERR_BANNEDFROMCHAN                       474 // <channel> :<reason>
#define ERR_BADCHANNELKEY                        475 // <channel> :<reason>
#define ERR_BADCHANMASK                          476 // <channel> :<reason>
#define ERR_NOCHANMODES_RFC2812                  477 // <channel> :<reason>
#define ERR_NEEDREGGEDNICK_BAHAMUT_IRCU_UNREAL   477
#define ERR_BANLISTFULL                          478 // <channel> <char> :<reason>
#define ERR_BADCHANNAME_HYBRID                   479
#define ERR_LINKFAIL_UNREAL                      479
#define ERR_NOULINE_AUSTHEX                      480
#define ERR_CANNOTKNOCK_UNREAL                   480
#define ERR_NOPRIVILEGES                         481 // :<reason>
#define ERR_CHANOPRIVSNEEDED                     482 // <channel> :<reason>
#define ERR_CANTKILLSERVER                       483 // :<reason>
#define ERR_RESTRICTED_RFC2812                   484 // :<reason>
#define ERR_ISCHANSERVICE_UNDERNET               484
#define ERR_DESYNC_BAHAMUT_HYBRID_PTLINK         484
#define ERR_ATTACKDENY_UNREAL                    484
#define ERR_UNIQOPRIVSNEEDED                     485 // :<reason>
#define ERR_KILLDENY_UNREAL                      485
#define ERR_CANTKICKADMIN_PTLINK                 485
#define ERR_ISREALSERVICE_QUAKENET               485
#define ERR_NONONREG                             486
#define ERR_HTMDISABLED_UNREAL                   486
#define ERR_ACCOUNTONLY_QUAKENET                 486
#define ERR_CHANTOORECENT_IRCNET                 487
#define ERR_MSGSERVICES_BAHAMUT                  487
#define ERR_TSLESSCHAN_IRCNET                    488
#define ERR_VOICENEEDED_UNDERNET                 489
#define ERR_SECUREONLYCHAN_UNREAL                489
#define ERR_NOOPERHOST                           491 // :<reason>
#define ERR_NOFEATURE_IRCU                       493
#define ERR_BADFEATURE_IRCU                      494
#define ERR_BADLOGTYPE_IRCU                      495
#define ERR_BADLOGSYS_IRCU                       496
#define ERR_BADLOGVALUE_IRCU                     497
#define ERR_ISOPERLCHAN_IRCU                     498
#define ERR_CHANOWNPRIVNEEDED_UNREAL             499
#define ERR_UMODEUNKNOWNFLAG                     501 // :<reason>
#define ERR_USERSDONTMATCH                       502 // :<reason>
#define ERR_GHOSTEDCLIENT_HYBRID                 503
#define ERR_USERNOTONSERV                        504
#define ERR_SILELISTFULL_IRCU                    511
#define ERR_TOOMANYWATCH_BAHAMUT                 512
#define ERR_BADPING_IRCU                         513
#define ERR_INVALID_ERROR_IRCU                   514
#define ERR_TOOMANYDCC_BAHAMUT_UNREAL            514
#define ERR_BADEXPIRE_IRCU                       515
#define ERR_DONTCHEAT_IRCU                       516
#define ERR_DISABLED_IRCU                        517 // <command> :<info/reason>
#define ERR_NOINVITE_UNREAL                      518
#define ERR_LONGMASK_IRCU                        518
#define ERR_ADMONLY_UNREAL                       519
#define ERR_TOOMANYUSERS_IRCU                    519
#define ERR_OPERONLY_UNREAL                      520
#define ERR_MASKTOOWIDE_IRCU                     520
#define ERR_LISTSYNTAX_BAHAMUT                   521
#define ERR_WHOSYNTAX_BAHAMUT                    522
#define ERR_WHOLIMEXCEED_BAHAMUT                 523
#define ERR_QUARANTINED_IRCU                     524
#define ERR_OPERSPVERIFY_UNREAL                  524
#define ERR_REMOTEPFX_CAPAB_USERCMDPFX           525 // <nickname> :<reason>
#define ERR_PFXUNROUTABLE_CAPAB_USERCMDPFX       526 // <nickname> :<reason>
#define ERR_BADHOSTMASK_QUAKENET                 550
#define ERR_HOSTUNAVAIL_QUAKENET                 551
#define ERR_USINGSLINE_QUAKENET                  552
#define ERR_STATSSLINE_QUAKENET                  553
#define RPL_LOGON_BAHAMUT_UNREAL                 600
#define RPL_LOGOFF_BAHAMUT_UNREAL                601
#define RPL_WATCHOFF_BAHAMUT_UNREAL              602
#define RPL_WATCHSTAT_BAHAMUT_UNREAL             603
#define RPL_NOWON_BAHAMUT_UNREAL                 604
#define RPL_NOWOFF_BAHAMUT_UNREAL                605
#define RPL_WATCHLIST_BAHAMUT_UNREAL             606
#define RPL_ENDOFWATCHLIST_BAHAMUT_UNREAL        607
#define RPL_WATCHCLEAR_ULTIMATE                  608
#define RPL_MAPMORE_UNREAL                       610
#define RPL_ISOPER_ULTIMATE                      610
#define RPL_ISLOCOP_ULTIMATE                     611
#define RPL_ISNOTOPER_ULTIMATE                   612
#define RPL_ENDOFISOPER_ULTIMATE                 613
#define RPL_MAPMORE_PTLINK                       615
#define RPL_WHOISMODES_ULTIMATE                  615
#define RPL_WHOISHOST_ULTIMATE                   616
#define RPL_DCCSTATUS_BAHAMUT_UNREAL             617
#define RPL_WHOISBOT_ULTIMATE                    617
#define RPL_DCCLIST_BAHAMUT_UNREAL               618
#define RPL_ENDOFDCCLIST_BAHAMUT_UNREAL          619
#define RPL_WHOWASHOST_ULTIMATE                  619
#define RPL_DCCINFO_BAHAMUT_UNREAL               620
#define RPL_RULESSTART_ULTIMATE                  620
#define RPL_RULES_ULTIMATE                       621
#define RPL_ENDOFRULES_ULTIMATE                  622
#define RPL_MAPMORE_ULTIMATE                     623
#define RPL_OMOTDSTART_ULTIMATE                  624
#define RPL_OMOTD_ULTIMATE                       625
#define RPL_ENDOFOMOTD_ULTIMATE                  626
#define RPL_SETTINGS_ULTIMATE                    630
#define RPL_ENDOFSETTINGS_ULTIMATE               631
#define RPL_TRACEROUTE_HOP_KINEIRCD              660 // <target> <hop#> [<address> [<hostname> | '*'] <usec_ping>]
#define RPL_TRACEROUTE_START_KINEIRCD            661 // <target> <target_FQDN> <target_address> <max_hops>
#define RPL_MODECHANGEWARN_KINEIRCD              662 // ['+' | '-']<mode_char> :<warning>
#define RPL_CHANREDIR_KINEIRCD                   663 // <old_chan> <new_chan> :<info>
#define RPL_SERVMODEIS_KINEIRCD                  664 // <server> <modes> <parameters>..
#define RPL_OTHERUMODEIS_KINEIRCD                665 // <nickname> <modes>
#define RPL_ENDOF_GENERIC_KINEIRCD               666 // <command> [<parameter> ...] :<info>
#define RPL_WHOWASDETAILS_KINEIRCD               670 // <nick> <type> :<information>
#define RPL_WHOISSECURE_KINEIRCD                 671 // <nick> <type> [:<info>]
#define RPL_UNKNOWNMODES_ITHILDIN                672 // <modes> :<info>
#define RPL_CANNOTSETMODES_ITHILDIN              673 // <modes> :<info>
#define RPL_LUSERSTAFF_KINEIRCD                  678 // <staff_online_count> :<info>
#define RPL_TIMEONSERVERIS_KINEIRCD              679 // <seconds> [<nanoseconds> | '0'] <timezone> <flags> :<info>
#define RPL_NETWORKS_KINEIRCD                    682 // <name> <through_name> <hops> :<info>
#define RPL_YOURLANGUAGEIS_KINEIRCD              687 // <code(s)> :<info>
#define RPL_LANGUAGE_KINEIRCD                    688 // <code> <revision> <maintainer> <flags> * :<info>
#define RPL_WHOISSTAFF_KINEIRCD                  689 // :<info>
#define RPL_WHOISLANGUAGE_KINEIRCD               690 // <nick> <language codes>
#define RPL_MODLIST_RATBOX                       702 // <?> 0x<?> <?> <?>
#define RPL_ENDOFMODLIST_RATBOX                  703 // :<text>
#define RPL_HELPSTART_RATBOX                     704 // <command> :<text>
#define RPL_HELPTXT_RATBOX                       705 // <command> :<text>
#define RPL_ENDOFHELP_RATBOX                     706 // <command> :<text>
#define RPL_ETRACEFULL_RATBOX                    708 // <?> <?> <?> <?> <?> <?> <?> :<?>
#define RPL_ETRACE_RATBOX                        709 // <?> <?> <?> <?> <?> <?> :<?>
#define RPL_KNOCK_RATBOX                         710 // <channel> <nick>!<user>@<host> :<text>
#define RPL_KNOCKDLVR_RATBOX                     711 // <channel> :<text>
#define ERR_TOOMANYKNOCK_RATBOX                  712 // <channel> :<text>
#define ERR_CHANOPEN_RATBOX                      713 // <channel> :<text>
#define ERR_KNOCKONCHAN_RATBOX                   714 // <channel> :<text>
#define ERR_KNOCKDISABLED_RATBOX                 715 // :<text>
#define RPL_TARGUMODEG_RATBOX                    716 // <nick> :<info>
#define RPL_TARGNOTIFY_RATBOX                    717 // <nick> :<info>
#define RPL_UMODEGMSG_RATBOX                     718 // <nick> <user>@<host> :<info>
#define RPL_OMOTDSTART_RATBOX                    720 // :<text>
#define RPL_OMOTD_RATBOX                         721 // :<text>
#define RPL_ENDOFOMOTD_RATBOX                    722 // :<text>
#define ERR_NOPRIVS_RATBOX                       723 // <command> :<text>
#define RPL_TESTMARK_RATBOX                      724 // <nick>!<user>@<host> <?> <?> :<text>
#define RPL_TESTLINE_RATBOX                      725 // <?> <?> <?> :<?>
#define RPL_NOTESTLINE_RATBOX                    726 // <?> :<text>
#define RPL_XINFO_ITHILDIN                       771
#define RPL_XINFOSTART_ITHILDIN                  773
#define RPL_XINFOEND_ITHILDIN                    774
#define RPL_SASLSUCCESS                          903
#define ERR_SASLFAIL                             904
#define ERR_SASLTOOLONG                          905
#define ERR_SASLABORTED                          906
#define ERR_SASLALREADY                          907
#define ERR_CANNOTDOCOMMAND_UNREAL               972
#define ERR_CANNOTCHANGEUMODE_KINEIRCD           973 // <mode_char> :<reason>
#define ERR_CANNOTCHANGECHANMODE_KINEIRCD_UNREAL 974 // <mode_char> :<reason>
#define ERR_CANNOTCHANGESERVERMODE_KINEIRCD      975 // <mode_char> :<reason>
#define ERR_CANNOTSENDTONICK_KINEIRCD            976 // <nick> :<reason>
#define ERR_UNKNOWNSERVERMODE_KINEIRCD           977 // <modechar> :<info>
#define ERR_SERVERMODELOCK_KINEIRCD              979 // <target> :<info>
#define ERR_BADCHARENCODING_KINEIRCD             980 // <command> <charset> :<info>
#define ERR_TOOMANYLANGUAGES_KINEIRCD            981 // <max_langs> :<info>
#define ERR_NOLANGUAGE_KINEIRCD                  982 // <language_code> :<info>
#define ERR_TEXTTOOSHORT_KINEIRCD                983 // <command> :<info>
#define ERR_NUMERIC_ERR_BAHAMUT                  999
